import {
  Injectable,
  Logger,
  BadRequestException,
} from '@nestjs/common';
import OpenAI from 'openai';
import { PrismaService } from '../../database/prisma.service';

/**
 * Represents the structured clinical summary generated by the AI engine.
 */
export interface ClinicalSummary {
  patientId: string;
  patientName: string;
  generatedAt: string; // ISO 8601
  status: 'COMPLETADO' | 'ERROR';
  sections: {
    diagnosticos: string[];
    tratamientos: string[];
    alergias: string[];
    recomendaciones: string[];
  };
}

/**
 * Raw patient history data collected before summary generation.
 */
export interface PatientHistoryData {
  patientId: string;
  patientName: string;
  diagnosticos: string[];
  tratamientos: string[];
  alergias: string[];
  notas: { content: string; createdAt: Date }[];
}

/** Configuration constants for the AI service */
const AI_CONFIG = {
  /** Timeout per OpenAI API call in milliseconds */
  TIMEOUT_MS: 30_000,
  /** Retry delays with exponential backoff (in ms) */
  RETRY_DELAYS: [2_000, 4_000],
  /** OpenAI model to use */
  MODEL: 'gpt-4o-mini',
} as const;

@Injectable()
export class AIService {
  private readonly logger = new Logger(AIService.name);
  private openaiClient: OpenAI | null = null;

  constructor(private readonly prisma: PrismaService) {
    this.initOpenAIClient();
  }

  /**
   * Initializes the OpenAI client if the API key is configured.
   * If not configured, the service will use local fallback only.
   */
  private initOpenAIClient(): void {
    const apiKey = process.env.OPENAI_API_KEY;
    if (apiKey) {
      this.openaiClient = new OpenAI({
        apiKey,
        timeout: AI_CONFIG.TIMEOUT_MS,
      });
      this.logger.log('OpenAI client initialized successfully');
    } else {
      this.logger.warn(
        'OPENAI_API_KEY not configured. AI summary will use local fallback.',
      );
    }
  }

  /**
   * Generates a structured clinical summary for a patient.
   * Tries OpenAI API first with retry + exponential backoff.
   * Falls back to local regex-based extraction if LLM is unavailable.
   *
   * @validates Requirements 14.1, 14.2, 14.3, 14.4, 14.5
   */
  async generateSummary(patientId: string): Promise<ClinicalSummary> {
    // Collect patient history
    const historyData = await this.collectPatientHistory(patientId);

    // Validate that at least 1 note exists (Requirement 14.4)
    if (historyData.notas.length === 0) {
      throw new BadRequestException(
        'Se requiere al menos 1 nota de evolución para generar el resumen',
      );
    }

    // Try OpenAI API first, fall back to local if unavailable
    if (this.openaiClient) {
      try {
        const aiSummary = await this.generateWithOpenAI(historyData);
        return aiSummary;
      } catch (error) {
        this.logger.warn(
          `OpenAI API failed after retries, using local fallback: ${error instanceof Error ? error.message : 'Unknown error'}`,
        );
      }
    }

    // Local fallback (Requirement 14.5)
    const summary = this.buildSummary(historyData);
    return summary;
  }

  /**
   * Calls OpenAI API with retry and exponential backoff.
   * Retries up to 2 times with delays of 2s and 4s.
   * Each call has a 30s timeout.
   *
   * @validates Requirements 14.2, 14.5
   */
  private async generateWithOpenAI(
    historyData: PatientHistoryData,
  ): Promise<ClinicalSummary> {
    const prompt = this.buildOpenAIPrompt(historyData);
    let lastError: Error | null = null;

    // Initial attempt + retries with exponential backoff
    const attempts = 1 + AI_CONFIG.RETRY_DELAYS.length;
    for (let attempt = 0; attempt < attempts; attempt++) {
      try {
        const result = await this.callOpenAI(prompt);
        return this.parseOpenAIResponse(result, historyData);
      } catch (error) {
        lastError = error instanceof Error ? error : new Error(String(error));
        this.logger.warn(
          `OpenAI attempt ${attempt + 1}/${attempts} failed: ${lastError.message}`,
        );

        // Wait before retrying (if there are more attempts)
        if (attempt < AI_CONFIG.RETRY_DELAYS.length) {
          await this.sleep(AI_CONFIG.RETRY_DELAYS[attempt]);
        }
      }
    }

    throw lastError || new Error('OpenAI API failed after all retries');
  }

  /**
   * Makes a single call to the OpenAI API with the configured timeout.
   */
  private async callOpenAI(prompt: string): Promise<string> {
    if (!this.openaiClient) {
      throw new Error('OpenAI client not initialized');
    }

    const response = await this.openaiClient.chat.completions.create({
      model: AI_CONFIG.MODEL,
      messages: [
        {
          role: 'system',
          content:
            'Eres un asistente médico que genera resúmenes clínicos estructurados. ' +
            'Responde SOLO con un JSON válido sin markdown ni texto adicional.',
        },
        { role: 'user', content: prompt },
      ],
      temperature: 0.3,
      response_format: { type: 'json_object' },
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error('Empty response from OpenAI');
    }

    return content;
  }

  /**
   * Builds the structured prompt for OpenAI with the patient's history.
   */
  private buildOpenAIPrompt(historyData: PatientHistoryData): string {
    const last10Notes = historyData.notas.slice(0, 10);
    const notesText = last10Notes
      .map(
        (n, i) =>
          `Nota ${i + 1} (${n.createdAt.toISOString().split('T')[0]}): ${n.content}`,
      )
      .join('\n');

    return `Genera un resumen clínico estructurado para el paciente "${historyData.patientName}".

DATOS DEL PACIENTE:
- Diagnósticos registrados: ${historyData.diagnosticos.length > 0 ? historyData.diagnosticos.join(', ') : 'Ninguno registrado'}
- Tratamientos/Prescripciones: ${historyData.tratamientos.length > 0 ? historyData.tratamientos.join(', ') : 'Ninguno registrado'}
- Alergias: ${historyData.alergias.length > 0 ? historyData.alergias.join(', ') : 'Ninguna registrada'}

ÚLTIMAS ${last10Notes.length} NOTAS DE EVOLUCIÓN:
${notesText}

INSTRUCCIONES:
Responde con un JSON con esta estructura exacta:
{
  "diagnosticos": ["lista de TODOS los diagnósticos del paciente"],
  "tratamientos": ["lista de TODOS los tratamientos/prescripciones"],
  "alergias": ["lista de TODAS las alergias"],
  "recomendaciones": ["recomendaciones basadas en las últimas notas de evolución"]
}

REGLAS:
- Incluye TODOS los diagnósticos proporcionados en los datos
- Incluye TODOS los tratamientos proporcionados
- Incluye TODAS las alergias proporcionadas
- Las recomendaciones deben basarse SOLO en las últimas 10 notas
- Si no hay datos en una sección, devuelve un array vacío []`;
  }

  /**
   * Parses the OpenAI response JSON into a ClinicalSummary.
   * Falls back to local buildSummary if parsing fails.
   */
  private parseOpenAIResponse(
    responseContent: string,
    historyData: PatientHistoryData,
  ): ClinicalSummary {
    try {
      const parsed = JSON.parse(responseContent);

      // Validate the response has the expected structure
      const sections = {
        diagnosticos: Array.isArray(parsed.diagnosticos)
          ? parsed.diagnosticos.filter((d: unknown) => typeof d === 'string' && d.trim().length > 0)
          : historyData.diagnosticos,
        tratamientos: Array.isArray(parsed.tratamientos)
          ? parsed.tratamientos.filter((t: unknown) => typeof t === 'string' && t.trim().length > 0)
          : historyData.tratamientos,
        alergias: Array.isArray(parsed.alergias)
          ? parsed.alergias.filter((a: unknown) => typeof a === 'string' && a.trim().length > 0)
          : historyData.alergias,
        recomendaciones: Array.isArray(parsed.recomendaciones)
          ? parsed.recomendaciones.filter((r: unknown) => typeof r === 'string' && r.trim().length > 0)
          : [],
      };

      return {
        patientId: historyData.patientId,
        patientName: historyData.patientName,
        generatedAt: new Date().toISOString(),
        status: 'COMPLETADO',
        sections,
      };
    } catch (parseError) {
      this.logger.warn(
        `Failed to parse OpenAI response, using local fallback: ${parseError instanceof Error ? parseError.message : 'Unknown error'}`,
      );
      return this.buildSummary(historyData);
    }
  }

  /**
   * Sleeps for a given duration (used for retry backoff).
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  /**
   * Collects the complete patient history from the database:
   * - All clinical notes (sorted by date desc)
   * - All allergies
   * - All prescriptions (treatments)
   *
   * Diagnoses and recommendations are extracted from clinical notes.
   */
  async collectPatientHistory(patientId: string): Promise<PatientHistoryData> {
    const patient = await this.prisma.patient.findUnique({
      where: { id: patientId },
      include: {
        allergies: true,
        clinicalNotes: {
          orderBy: { createdAt: 'desc' },
        },
        prescriptions: true,
      },
    });

    if (!patient) {
      throw new BadRequestException(
        `Paciente con ID ${patientId} no encontrado`,
      );
    }

    // Extract diagnoses from notes content (lines starting with "Diagnóstico:" or "DX:")
    const diagnosticos = this.extractDiagnosticos(patient.clinicalNotes);

    // Treatments come from prescriptions
    const tratamientos = patient.prescriptions.map((p) => p.content);

    // Allergies from allergies table
    const alergias = patient.allergies.map((a) => a.description);

    // Notes for recommendations (already sorted desc)
    const notas = patient.clinicalNotes.map((n) => ({
      content: n.content,
      createdAt: n.createdAt,
    }));

    return {
      patientId: patient.id,
      patientName: patient.fullName,
      diagnosticos,
      tratamientos,
      alergias,
      notas,
    };
  }

  /**
   * Builds the structured clinical summary from collected history data.
   * Includes:
   * - ALL diagnoses registered in the file
   * - ALL treatments performed
   * - ALL registered allergies
   * - Recommendations from the last 10 evolution notes
   *
   * @validates Requirements 14.1, 14.3
   */
  buildSummary(historyData: PatientHistoryData): ClinicalSummary {
    // Get recommendations from the last 10 notes
    const last10Notes = historyData.notas.slice(0, 10);
    const recomendaciones = this.extractRecomendaciones(last10Notes);

    return {
      patientId: historyData.patientId,
      patientName: historyData.patientName,
      generatedAt: new Date().toISOString(),
      status: 'COMPLETADO',
      sections: {
        diagnosticos: historyData.diagnosticos,
        tratamientos: historyData.tratamientos,
        alergias: historyData.alergias,
        recomendaciones,
      },
    };
  }

  /**
   * Extracts diagnoses from clinical notes.
   * Looks for lines containing "Diagnóstico:" or "DX:" patterns.
   */
  private extractDiagnosticos(
    notes: { content: string; createdAt: Date }[],
  ): string[] {
    const diagnosticos: string[] = [];
    const diagRegex = /(?:diagnóstico|diagnostico|dx)\s*:\s*(.+)/gi;

    for (const note of notes) {
      let match: RegExpExecArray | null;
      while ((match = diagRegex.exec(note.content)) !== null) {
        const diag = match[1].trim();
        if (diag.length > 0 && !diagnosticos.includes(diag)) {
          diagnosticos.push(diag);
        }
      }
    }

    return diagnosticos;
  }

  /**
   * Extracts recommendations from the last 10 notes.
   * Looks for lines containing "Recomendación:" or "Recomendaciones:" patterns.
   */
  private extractRecomendaciones(
    notes: { content: string; createdAt: Date }[],
  ): string[] {
    const recomendaciones: string[] = [];
    const recRegex = /(?:recomendación|recomendacion|recomendaciones)\s*:\s*(.+)/gi;

    for (const note of notes) {
      let match: RegExpExecArray | null;
      while ((match = recRegex.exec(note.content)) !== null) {
        const rec = match[1].trim();
        if (rec.length > 0 && !recomendaciones.includes(rec)) {
          recomendaciones.push(rec);
        }
      }
    }

    return recomendaciones;
  }
}
