export { KioskWizard } from './KioskWizard';
export { SignaturePad } from './components/SignaturePad';
export { useKioskInactivity } from './hooks/useKioskInactivity';
export { PersonalDataStep } from './steps/PersonalDataStep';
export { MedicalHistoryStep } from './steps/MedicalHistoryStep';
export { EmergencyContactStep } from './steps/EmergencyContactStep';
export { PrivacyNoticeStep } from './steps/PrivacyNoticeStep';
export { SignatureStep } from './steps/SignatureStep';
export type { PersonalData } from './steps/PersonalDataStep';
export type { MedicalHistoryData } from './steps/MedicalHistoryStep';
export type { EmergencyContactData } from './steps/EmergencyContactStep';
export type { SignaturePadProps } from './components/SignaturePad';
